namespace: monitoring


# 7am UTC = 2am EST
schedule: "0 7 * * *"

image:
  registry: registry
  name: kfp-secret-scanner
  version: "1.9"

  imagePullSecrets: []
  #- name: image-pull-secret

# If you run the script interactively,
elasticsearch:
  host: http://elastic
  index: 'kubeflow-pipeline-secrets'

secretscan:
  max_entropy: "3.5"
