apiVersion: v1
data:
  ES_USER: {{ .Values.elkSecret.elkUser | b64enc }}
  ES_PASS: {{ .Values.elkSecret.elkPass | b64enc }}
kind: Secret
metadata:
  name: {{ .Values.elkSecret.secretName }}
  namespace: {{ .Values.namespace }}
type: Opaque
